# Generated by Django 5.0.4 on 2024-04-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=20)),
                ('mobile_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('WOMEN', 'women'), ('MEN', 'men'), ('BOY', 'boy'), ('GIRL', 'girl')], max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('seat_no', models.CharField(max_length=10)),
                ('fight_time', models.TimeField()),
            ],
        ),
    ]
